[package]
name = "dd-monitor"
version = "0.1.0"
authors = ["Jeremy Banks <_@jeremy.ca>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
atty = "0.2.14"
csv = "1.1.3"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.56"
thiserror = "1.0.20"
