[package]
name = "dd-monitor"
version = "0.1.0"
authors = ["Jeremy Banks <_@jeremy.ca>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
argh = "0.1.3"
thiserror = "1.0.20"
serde = "1.0.114"
csv = "1.1.3"
serde_derive = "1.0.114"
