#!/bin/bash
# shellcheck source=base.bash
source /dev/null; eval "$(cat "$(dirname -- "$0")/base.bash")"

cd ./ideas;

declare name filename;
for filename in *.bash; do
  name="${filename%.bash}"
  chmod --verbose +x "$filename"
  for source in "$name.md" "$name.txt"; do
    cp --verbose --symbolic-link --force "$filename" "$source"
  done
  (cd ..; cp --verbose --symbolic-link --force "ideas/$filename" "$name")
done
