#!/bin/bash
# shellcheck source=base.bash
source /dev/null; eval "$(cat "$(dirname -- "$0")/base.bash")"

cd ./ideas;

declare name filename;
for filename in *.bash; do
  name="${filename%.bash}"
  chmod --verbose +x "$filename"
  for extension in md txt; do
    cp --verbose --symbolic-link --force "$filename" "$name.$extension"
  done
done
