#!/bin/bash
# shellcheck source=base.bash
source /dev/null; eval "$(cat "$(dirname -- "$0")/base.bash")"

declare name status

for suite in "$PWD"/**/*.tests; do
  echo "$suite" >&2
  cd "$suite"
  for test in ./*.bash; do
    echo "$test" >&2
    name="${test%.*}"
    rm -rf "$name.status.txt"
    rm -rf "$name.stdout.txt"
    rm -rf "$name.stderr.txt"
    if [[ ! -e "$name.stdin.txt" ]]; then
      touch "$name.stdin.txt"
    fi
    status=0
    bash "$test" <"$name.stdin.txt" 1>"$name.stdout.txt" 2>"$name.stderr.txt" || status="$?"
    echo "$status" > "$name.status.txt"
  done
  git add --intent-to-add "$suite"
  git --no-pager diff --compact-summary HEAD -- "$suite"
  echo
done
