#!/bin/bash
eval "$(cat "$(dirname -- "$0")/lib")"
# shellcheck source=lib
source /dev/null

if [[ "$__owd__" == "$__dir__" ]]; then
  echo "FATAL: Run this from the root of a repo you want to install/update into."
  exit 1
fi

set -x

cd "$__owd__"

# Ensure we're at the root of a git repository
test -d .git
git status

declare repo=https://github.com/jeremyBanks/banksh
declare path=.banksh
declare add_or_pull
if [[ -d $path ]]; then
  add_or_pull=pull
else
  add_or_pull=add
fi

git subtree $add_or_pull --squash --prefix="$path" "$repo" HEAD
