#!/bin/bash

{ # Check preconditions and set Bash settings.
  if (( "${BASH_VERSINFO[0]:-0}" <= 3 )); then
   echo "FATAL: bash>=4.2 required, but using: $("$(command -v "$(ps -cp "$$" -o command=)")" --version)"
   exit 1
  elif [[ "$(basename "${BASH_SOURCE[0]}")" == "base" ]]; then
   echo 'FATAL: base should be evaled, not sourced'
   exit 1
  elif [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
   echo "FATAL: ${BASH_SOURCE[0]} is a script, not a library. Execute it, don't source it."
   exit 1
  fi

  # shellcheck disable=SC2034
  declare -r BASH_COMPAT=4.2

  declare -x LC_ALL=C.UTF-8
  declare -x LANGUAGE=

  set -o monitor -o pipefail -o errexit -o errtrace -o functrace -o nounset -o noclobber
  shopt -s nullglob globstar expand_aliases
  shopt -u sourcepath globasciiranges
}

{ # Declare global constants.
  declare __owd__ __file__ __name__ __dir__ __argv__
  __owd__="$(realpath "$(pwd)")"
  __file__="$(realpath "${BASH_SOURCE[0]}")"
  __name__="$(basename "${__file__}")"
  __dir__="$(dirname "${__file__}")"
  __argv__=("$@")
  declare -r __owd__ __file__ __name__ __dir__ __argv__
}

{ # Set working directorylo.
  cd "${__dir__}"
}

{ # Set environment variables.
  declare -rx TERM="${TERM=dumb}"

  if [[ "${CI:-}" == "true" ]]; then
   declare -rx CI=true
  else
   declare -r +x CI=false
  fi
}
